### ISSUE TITLE
Parsing edge-case

### ISSUE THREAD

**Issue by ukutaht** [elixytics/ref_inspector#2]
Hey, first of all thanks for the library, it's really useful.

I noticed today that when parsing websites whose domain ends with `t.co` but that aren't actually Twitter get categorized wrong. Here's an example:
```
> RefInspector.parse("http://not-twitter.co")
%RefInspector.Result{
  medium: :unknown,
  referer: "http://not-twitter.co",
  source: :unknown,
  term: :none
}
> RefInspector.parse("http://not-twitter-but-ends-with-t.co")
%RefInspector.Result{
  medium: "social",
  referer: "http://not-twitter-but-ends-with-t.co",
  source: "Twitter",
  term: :none
}
```

I took a quick peek at the code and I'm guessing because of the `String.ends_with?` [here](https://github.com/elixir-inspector/ref_inspector/blob/master/lib/ref_inspector/parser.ex#L49). Is this a performance optimization?

Another example, the website `nomoregoogle.com` would be parsed as `Google` when it's clearly not :)

Any ideas on how to fix that? Happy to send a PR.

**Comment by mneudert** [comment]
Looking at how both the domains and path are matched that is sort of completely broken since... ever.

Could you take a look at the referenced commit (branch `v1.3`) to double check that this fixes the problem? If you can think of a more simple way to have the parsing do what one would actually expect please just send a PR with the `v1.3` branch as the base :)

**Comment by ukutaht** [comment]
Can confirm that v1.3 fixes the issue I'm seeing. Thanks for the quick response on this, I'll stay tuned for a public release.
